### PR TITLE
Modernize addon

### PR DESCRIPTION
**Pull request by calvinlough**
Bring the changes in https://github.com/calvinlough/ember-tag-input/pull/208 across the finish line.

### CODE REVIEW

**Comment by heipei** [comment]
Would be great to get this merged and pushed as a release @calvinlough, currently stuck because I use this addon and can't finish the upgrade to Ember 4.4.0

**Comment by calvinlough** [comment]
Sorry about that @heipei. I forget where I got stuck on this one, I'll take another look soon.

**Comment by calvinlough** [comment]
@heipei This has been released as 3.0.0. Let me know if you have any issues with it.

**Comment by heipei** [comment]
Hello @calvinlough, I really appreciate the effort, thank you!

**Pull request merged**
